#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml
    - secrets.yml

  tasks:
    - ec2_instance_fact:
        region: "{{ aws_region }}"
